const publicMapStub = ({
  id,
  slug,
  entityType = "location",
  title,
  sourcePath,
  mapMarker,
  mapRegion,
  mapLabel,
}) => ({
  id,
  slug,
  entityType,
  canonicalName: title,
  publicTitle: title,
  publicSummary: `${title} is catalogued as map reference ${mapMarker} on the illustrated city chart. This stub preserves the mapped public name while a fuller source-grounded extract is prepared.`,
  previewStatus: "proposal",
  spoilerClassification: "public",
  archiveSection: "public",
  sourcePaths: [sourcePath],
  mapMarker,
  mapRegion,
  mapLabel,
  relatedEntryIds: ["location-aetherhaven"],
  tags: ["map-location", `map-${mapMarker}`],
});

export const publicMapEntries = [
  publicMapStub({ id: "location-aetherium", slug: "aetherium", title: "The Aetherium", sourcePath: "locations/The_Aetherium.md", mapMarker: "1", mapRegion: { cx: 770, cy: 500, r: 92 }, mapLabel: { x: 710, y: 458, width: 120, height: 54 } }),
  publicMapStub({ id: "location-clockwork-gardens", slug: "clockwork-gardens", title: "The Clockwork Gardens", sourcePath: "locations/The_Clockwork_Gardens.md", mapMarker: "2", mapRegion: { cx: 770, cy: 596, r: 96 }, mapLabel: { x: 706, y: 566, width: 128, height: 58 } }),
  publicMapStub({ id: "location-grand-atrium", slug: "grand-atrium", title: "The Grand Atrium", sourcePath: "locations/The_Grand_Atrium.md", mapMarker: "3", mapRegion: { cx: 972, cy: 463, r: 82 }, mapLabel: { x: 914, y: 438, width: 126, height: 54 } }),
  publicMapStub({ id: "location-clocktower-spire", slug: "clocktower-spire", title: "The Clocktower Spire", sourcePath: "locations/The_Clocktower_Spire.md", mapMarker: "4", mapRegion: { cx: 770, cy: 326, r: 76 }, mapLabel: { x: 705, y: 296, width: 130, height: 60 } }),
  publicMapStub({ id: "location-waterfall-cascades", slug: "waterfall-cascades", title: "The Waterfall Cascades", sourcePath: "locations/The_Waterfall_Cascades.md", mapMarker: "5", mapRegion: { cx: 454, cy: 183, r: 82 }, mapLabel: { x: 390, y: 150, width: 132, height: 62 } }),
  publicMapStub({ id: "location-reflection-canals", slug: "reflection-canals", title: "The Reflection Canals", sourcePath: "locations/The_Reflection_Canals.md", mapMarker: "6", mapRegion: { cx: 599, cy: 466, r: 90 }, mapLabel: { x: 535, y: 438, width: 128, height: 56 } }),
  publicMapStub({ id: "location-starlight-walkways", slug: "starlight-walkways", title: "The Starlight Walkways", sourcePath: "locations/The_Starlight_Walkways.md", mapMarker: "7", mapRegion: { cx: 666, cy: 667, r: 84 }, mapLabel: { x: 600, y: 640, width: 132, height: 56 } }),
  publicMapStub({ id: "location-gardens-airship-landing", slug: "gardens-airship-landing", title: "The Gardens Airship Landing", sourcePath: "locations/The_Gardens_Airship_Landing.md", mapMarker: "8", mapRegion: { cx: 431, cy: 686, r: 100 }, mapLabel: { x: 366, y: 654, width: 130, height: 64 } }),
  publicMapStub({ id: "location-southern-docks", slug: "southern-docks", title: "The Southern Docks", sourcePath: "locations/The_Southern_Docks.md", mapMarker: "9", mapRegion: { cx: 1008, cy: 843, r: 92 }, mapLabel: { x: 946, y: 812, width: 124, height: 62 } }),
  publicMapStub({ id: "location-brass-gate", slug: "brass-gate", title: "The Brass Gate", sourcePath: "locations/The_Brass_Gate.md", mapMarker: "10", mapRegion: { cx: 774, cy: 899, r: 88 }, mapLabel: { x: 715, y: 870, width: 118, height: 58 } }),
  publicMapStub({ id: "district-government", slug: "government-district", entityType: "district", title: "The Government District", sourcePath: "locations/The_Government_District.md", mapMarker: "11", mapRegion: { cx: 612, cy: 232, r: 90 }, mapLabel: { x: 548, y: 204, width: 128, height: 58 } }),
  publicMapStub({ id: "district-merchant", slug: "merchant-district", entityType: "district", title: "The Merchant District", sourcePath: "locations/The_Merchant_District.md", mapMarker: "12", mapRegion: { cx: 450, cy: 342, r: 94 }, mapLabel: { x: 386, y: 314, width: 128, height: 58 } }),
  publicMapStub({ id: "district-inventors", slug: "inventors-district", entityType: "district", title: "The Inventors’ District", sourcePath: "locations/The_Inventors_District.md", mapMarker: "13", mapRegion: { cx: 882, cy: 274, r: 94 }, mapLabel: { x: 814, y: 244, width: 136, height: 60 } }),
  publicMapStub({ id: "district-industrial", slug: "industrial-district", entityType: "district", title: "The Industrial District", sourcePath: "locations/The_Industrial_District.md", mapMarker: "14", mapRegion: { cx: 1203, cy: 419, r: 90 }, mapLabel: { x: 1137, y: 390, width: 132, height: 58 } }),
  publicMapStub({ id: "location-old-city", slug: "old-city", title: "The Old City", sourcePath: "locations/The_Old_City.md", mapMarker: "15", mapRegion: { cx: 362, cy: 514, r: 92 }, mapLabel: { x: 306, y: 486, width: 112, height: 56 } }),
  publicMapStub({ id: "district-canal", slug: "canal-district", entityType: "district", title: "The Canal District", sourcePath: "locations/The_Canal_District.md", mapMarker: "16", mapRegion: { cx: 922, cy: 705, r: 94 }, mapLabel: { x: 861, y: 676, width: 122, height: 58 } }),
  publicMapStub({ id: "district-entertainment", slug: "entertainment-district", entityType: "district", title: "The Entertainment District", sourcePath: "locations/The_Entertainment_District.md", mapMarker: "17", mapRegion: { cx: 542, cy: 838, r: 94 }, mapLabel: { x: 474, y: 808, width: 136, height: 60 } }),
  publicMapStub({ id: "location-workers-dormitories", slug: "workers-dormitories", title: "The Workers’ Dormitories", sourcePath: "locations/The_Workers_Dormitories.md", mapMarker: "18", mapRegion: { cx: 1203, cy: 610, r: 94 }, mapLabel: { x: 1134, y: 578, width: 138, height: 64 } }),
  publicMapStub({ id: "location-aerial-docks", slug: "aerial-docks", title: "The Aerial Docks", sourcePath: "locations/The_Aerial_Docks.md", mapMarker: "19", mapRegion: { cx: 337, cy: 282, r: 96 }, mapLabel: { x: 280, y: 252, width: 114, height: 60 } }),
  publicMapStub({ id: "location-great-workshops", slug: "great-workshops", title: "The Great Workshops", sourcePath: "locations/The_Great_Workshops.md", mapMarker: "20", mapRegion: { cx: 1100, cy: 231, r: 88 }, mapLabel: { x: 1035, y: 202, width: 130, height: 58 } }),
  publicMapStub({ id: "location-engine-complex", slug: "engine-complex", title: "The Engine Complex", sourcePath: "locations/The_Engine_Complex.md", mapMarker: "21", mapRegion: { cx: 1302, cy: 472, r: 88 }, mapLabel: { x: 1238, y: 444, width: 128, height: 56 } }),
  publicMapStub({ id: "location-gearbreaker-mines", slug: "gearbreaker-mines", title: "The Gearbreaker Mines", sourcePath: "locations/The_Gearbreaker_Mines.md", mapMarker: "22", mapRegion: { cx: 1420, cy: 202, r: 84 }, mapLabel: { x: 1356, y: 174, width: 128, height: 58 } }),
  publicMapStub({ id: "location-observatory", slug: "observatory", title: "The Observatory", sourcePath: "locations/The_Observatory.md", mapMarker: "23", mapRegion: { cx: 458, cy: 987, r: 92 }, mapLabel: { x: 402, y: 958, width: 112, height: 58 } }),
  publicMapStub({ id: "location-academy-of-invention", slug: "academy-of-invention-campus", title: "The Academy of Invention", sourcePath: "locations/The_Academy_of_Invention_Campus.md", mapMarker: "24", mapRegion: { cx: 1259, cy: 237, r: 86 }, mapLabel: { x: 1194, y: 208, width: 130, height: 58 } }),
];

const publicEntityStub = ({ id, slug, entityType, title, canonicalName = title, publicSummary, sourcePath, tags = [] }) => ({
  id,
  slug,
  entityType,
  canonicalName,
  publicTitle: title,
  publicSummary,
  previewStatus: "proposal",
  spoilerClassification: "public",
  archiveSection: "public",
  sourcePaths: [sourcePath],
  relatedEntryIds: [],
  tags: [entityType, "catalog-stub", ...tags],
});

export const publicCharacterEntries = [
  publicEntityStub({ id: "character-amelia-hawthorne", slug: "amelia-hawthorne", entityType: "character", title: "Amelia Hawthorne", publicSummary: "Amelia Hawthorne is a young mechanic and apprentice explorer who lives and travels aboard the Wayfinder with her father, Professor Elias Hawthorne.", sourcePath: "characters/Amelia_Hawthorne.md" }),
  publicEntityStub({ id: "character-barnaby-wren", slug: "barnaby-wren", entityType: "character", title: "Barnaby Wren", publicSummary: "Barnaby Wren is the proprietor of the Last Lantern, the oldest shop in Aetherhaven’s Merchant District.", sourcePath: "characters/Barnaby_Wren.md" }),
  publicEntityStub({ id: "character-beatrice-pike", slug: "beatrice-pike", entityType: "character", title: "Beatrice Pike", publicSummary: "Beatrice Pike is a Pike family name preserved on the plate for Tamsin Pike’s brass key; no further biography is established.", sourcePath: "characters/Beatrice_Pike.md" }),
  publicEntityStub({ id: "character-captain-mara-voss", slug: "captain-mara-voss", entityType: "character", title: "Captain Mara Voss", publicSummary: "Captain Mara Voss is Aetherhaven’s Harbormaster, responsible for the city’s aerial traffic, docks, and emergency landing decisions.", sourcePath: "characters/Captain_Mara_Voss.md" }),
  publicEntityStub({ id: "character-chancellor-octavia-vale", slug: "chancellor-octavia-vale", entityType: "character", title: "Chancellor Octavia Vale", publicSummary: "Chancellor Octavia Vale is the disciplined presiding officer of Aetherhaven’s High Council.", sourcePath: "characters/Chancellor_Octavia_Vale.md" }),
  publicEntityStub({ id: "character-chief-inspector-beatrice-thorne", slug: "chief-inspector-beatrice-thorne", entityType: "character", title: "Chief Inspector Beatrice Thorne", publicSummary: "Chief Inspector Beatrice Thorne commands the Brass Watch and oversees Aetherhaven’s investigations, patrols, and emergency response.", sourcePath: "characters/Chief_Inspector_Beatrice_Thorne.md" }),
  publicEntityStub({ id: "character-doctor-elara-quill", slug: "doctor-elara-quill", entityType: "character", title: "Doctor Elara Quill", publicSummary: "Doctor Elara Quill is Chancellor of the Academy of Invention and one of Aetherhaven’s leading scholars.", sourcePath: "characters/Doctor_Elara_Quill.md" }),
  publicEntityStub({ id: "character-euphemia-pike", slug: "euphemia-pike", entityType: "character", title: "Euphemia Pike", publicSummary: "Euphemia Pike is a Pike family name preserved on the plate for Tamsin Pike’s brass key; no further biography is established.", sourcePath: "characters/Euphemia_Pike.md" }),
  publicEntityStub({ id: "character-juniper-bell", slug: "juniper-bell", entityType: "character", title: "Juniper Bell", publicSummary: "Juniper Bell is the gentle and eccentric public Keeper of the Clockwork Gardens.", sourcePath: "characters/Juniper_Bell.md" }),
  publicEntityStub({ id: "character-lucian-wren", slug: "lucian-wren", entityType: "character", title: "Lucian Wren", publicSummary: "Lucian Wren is a celebrated public inventor whose theatrical demonstrations attract crowds throughout Aetherhaven.", sourcePath: "characters/Lucian_Wren.md" }),
  publicEntityStub({ id: "character-madame-celestine-mirrow", slug: "madame-celestine-mirrow", entityType: "character", title: "Madame Celestine Mirrow", publicSummary: "Madame Celestine Mirrow is the elegant mistress of the Theatre of Impossible Things.", sourcePath: "characters/Madame_Celestine_Mirrow.md" }),
  publicEntityStub({ id: "character-master-gideon-brasswell", slug: "master-gideon-brasswell", entityType: "character", title: "Master Gideon Brasswell", publicSummary: "Master Gideon Brasswell is the respected Keeper of the Engine Complex and a veteran engineer trusted by Aetherhaven’s workers.", sourcePath: "characters/Master_Gideon_Brasswell.md" }),
  publicEntityStub({ id: "character-orin-flint", slug: "orin-flint", entityType: "character", title: "Orin Flint", publicSummary: "Orin Flint is the veteran foreman of the Gearbreaker Mines and a steadfast advocate for the safety of his crews.", sourcePath: "characters/Orin_Flint.md" }),
  publicEntityStub({ id: "character-pip", slug: "pip", entityType: "character", title: "Pip", publicSummary: "Pip is Amelia Hawthorne’s curious brass sparrow companion aboard the Wayfinder.", sourcePath: "characters/Pip.md" }),
  publicEntityStub({ id: "character-professor-elias-hawthorne", slug: "professor-elias-hawthorne", entityType: "character", title: "Professor Elias Hawthorne", publicSummary: "Professor Elias Hawthorne is an engineer, archaeologist, explorer, father, and the figure publicly known as the Brass Guardian.", sourcePath: "characters/Professor_Elias_Hawthorne.md" }),
  publicEntityStub({ id: "character-tamsin-pike", slug: "tamsin-pike", entityType: "character", title: "Tamsin Pike", publicSummary: "Tamsin Pike is a capable young canal guide and locksmith with practical knowledge of Aetherhaven’s waterways and maintenance passages.", sourcePath: "characters/Tamsin_Pike.md" }),
];

export const publicOrganizationEntries = [
  ["academy-of-invention", "The Academy of Invention", "The Academy of Invention is Aetherhaven’s principal institution for engineering education, experimental research, and the preservation of unfinished ideas.", "The_Academy_of_Invention.md"],
  ["aerial-mariners-union", "The Aerial Mariners’ Union", "The Aerial Mariners’ Union represents the crews and workers who keep Aetherhaven connected to the skies while providing certification, rescue, and mutual aid.", "The_Aerial_Mariners_Union.md"],
  ["aetherhaven-archives", "The Aetherhaven Archives", "The Aetherhaven Archives is the civic institution responsible for official records, transit documents, historical materials, and artifact custody.", "The_Aetherhaven_Archives.md"],
  ["brass-watch", "The Brass Watch", "The Brass Watch is Aetherhaven’s constabulary, emergency service, investigative authority, and canal patrol.", "The_Brass_Watch.md"],
  ["conclave-of-eight", "The Conclave of Eight", "The Conclave of Eight brings together the eight founding guildmasters to coordinate technical standards and advise Aetherhaven’s government.", "The_Conclave_of_Eight.md"],
  ["conservancy-of-living-mechanisms", "The Conservancy of Living Mechanisms", "The Conservancy is a pacifist fellowship of gardeners, healers, and mechanists who care for the Clockwork Gardens and their living machines.", "The_Conservancy_of_Living_Mechanisms.md"],
  ["eight-founding-engineering-guilds", "The Eight Founding Engineering Guilds", "The Eight Founding Engineering Guilds are Aetherhaven’s original civic engineering orders, each responsible for an essential technical discipline.", "The_Eight_Founding_Engineering_Guilds.md"],
  ["free-spring-assembly", "The Free Spring Assembly", "The Free Spring Assembly is a public reform wing of the Unwound associated with petitions, debate, transparency, and accountable infrastructure.", "The_Free_Spring_Assembly.md"],
  ["guild-of-aetherwrights", "The Guild of Aetherwrights", "The Guild of Aetherwrights oversees aetherstone, conduits, Golden Veins, and the controlled movement of aetheric power.", "The_Guild_of_Aetherwrights.md"],
  ["guild-of-artificers", "The Guild of Artificers", "The Guild of Artificers specializes in automata, prosthetics, optics, precision devices, and advanced mechanical craft.", "The_Guild_of_Artificers.md"],
  ["guild-of-canalwrights", "The Guild of Canalwrights", "The Guild of Canalwrights is responsible for Aetherhaven’s canals, locks, water systems, drainage, and sanitation.", "The_Guild_of_Canalwrights.md"],
  ["guild-of-clockwrights", "The Guild of Clockwrights", "The Guild of Clockwrights is responsible for clocks, synchronization, calendars, and the civic measurement of time.", "The_Guild_of_Clockwrights.md"],
  ["guild-of-enginewrights", "The Guild of Enginewrights", "The Guild of Enginewrights specializes in steam, pressure, turbines, heavy machinery, and engine systems.", "The_Guild_of_Enginewrights.md"],
  ["guild-of-framewrights", "The Guild of Framewrights", "The Guild of Framewrights oversees structures, architecture, foundations, and the physical frames supporting Aetherhaven.", "The_Guild_of_Framewrights.md"],
  ["guild-of-skywrights", "The Guild of Skywrights", "The Guild of Skywrights is responsible for airship design, lift systems, mooring towers, and aerial engineering.", "The_Guild_of_Skywrights.md"],
  ["guild-of-verdant-mechanists", "The Guild of Verdant Mechanists", "The Guild of Verdant Mechanists works with living machinery, botanical engineering, agricultural mechanisms, and systems joining growth with craft.", "The_Guild_of_Verdant_Mechanists.md"],
  ["handwright-circles", "The Handwright Circles", "The Handwright Circles are local Unwound groups that preserve handcraft, repair knowledge, and manual alternatives to automated systems.", "The_Handwright_Circles.md"],
  ["high-council-of-aetherhaven", "The High Council of Aetherhaven", "The High Council is Aetherhaven’s central governing body for law, trade, infrastructure, taxation, public safety, and civic relations.", "The_High_Council_of_Aetherhaven.md"],
  ["lamplighters-fellowship", "The Lamplighters’ Fellowship", "The Lamplighters’ Fellowship maintains Aetherhaven’s streetlamps, bridge lights, canal markers, public stair lamps, and aerial beacons.", "The_Lamplighters_Fellowship.md"],
  ["mechanists-guild", "The Mechanists’ Guild", "The Mechanists’ Guild is Aetherhaven’s professional engineering federation, certification authority, and civic machinery safety order.", "The_Mechanists_Guild.md"],
  ["miners-guild", "The Miners’ Guild", "The Miners’ Guild represents the workers associated with the Gearbreaker Mines, tunnel safety, extraction, and knowledge of the mountain.", "The_Miners_Guild.md"],
  ["order-of-the-mended-hand", "The Order of the Mended Hand", "The Mended Hand is Aetherhaven’s principal institution for severe medicine, surgery, trauma care, rehabilitation, prosthetics, and field response.", "The_Order_of_the_Mended_Hand.md"],
  ["severed-coil", "The Severed Coil", "The Severed Coil is a violent extremist splinter of the Unwound known publicly for attacking civic infrastructure and endangering bystanders.", "The_Severed_Coil.md"],
  ["society-of-explorers", "The Society of Explorers", "The Society of Explorers is a chartered institution associated with expedition credentials, maps, field reports, and the Hawthornes.", "The_Society_of_Explorers.md"],
  ["unwound", "The Unwound", "The Unwound is a broad reform movement seeking infrastructure that citizens can understand, repair, interrupt, and hold accountable.", "The_Unwound.md"],
].map(([slug, title, publicSummary, filename]) => publicEntityStub({
  id: `organization-${slug}`,
  slug,
  entityType: "organization",
  title,
  publicSummary,
  sourcePath: `organizations/${filename}`,
}));

const hiddenStub = ({ id, slug, entityType, title, sourcePath, sensitivity = "restricted", publicSummary }) => ({
  id,
  slug,
  entityType,
  canonicalName: title,
  publicTitle: title,
  publicSummary: publicSummary ?? `${title} has a restricted Archive reference. Identity, purpose, and fuller context remain sealed or withheld.`,
  previewStatus: "proposal",
  spoilerClassification: sensitivity,
  archiveSection: "hidden",
  sourcePaths: [sourcePath],
  relatedEntryIds: [],
  tags: [entityType, "hidden-archive"],
});

export const hiddenMapEntries = [
  ["A", "obsidian-spire", "The Obsidian Spire", "locations/The_Obsidian_Spire.md", { cx: 1416, cy: 124, r: 82 }, { x: 1338, y: 420, width: 162, height: 54 }, "Map annotation: “Off limits.” Further record sealed."],
  ["B", "shrouded-vaults", "The Shrouded Vaults", "locations/The_Shrouded_Vaults.md", { cx: 1309, cy: 745, r: 84 }, { x: 1338, y: 482, width: 162, height: 54 }, "Map annotation: “Access denied.” Further record sealed."],
  ["C", "echoing-depths", "The Echoing Depths", "locations/The_Echoing_Depths.md", { cx: 1266, cy: 877, r: 86 }, { x: 1338, y: 544, width: 162, height: 54 }, "Map annotation: “No one returns.” Further record sealed."],
  ["D", "silent-observatory", "The Silent Observatory", "locations/The_Silent_Observatory.md", { cx: 1416, cy: 340, r: 82 }, { x: 1338, y: 606, width: 162, height: 54 }, "Map annotation asks why the observatory is silent. Further record sealed."],
  ["E", "cauldron", "The Cauldron", "locations/The_Cauldron.md", { cx: 304, cy: 887, r: 88 }, { x: 1338, y: 668, width: 162, height: 54 }, "Map annotation records songs and screams. Further record sealed."],
  ["F", "null-zone", "The Null Zone", "locations/The_Null_Zone.md", { cx: 1298, cy: 983, r: 88 }, { x: 1338, y: 730, width: 162, height: 54 }, "Map annotation: “Machines fail here.” Further record sealed."],
].map(([mapMarker, slug, title, sourcePath, mapRegion, mapLabel, publicSummary]) => ({
  ...hiddenStub({ id: `restricted-${slug}`, slug, entityType: "restricted-location", title, sourcePath, sensitivity: "restricted", publicSummary }),
  mapMarker,
  mapRegion,
  mapLabel,
}));

export const hiddenCharacterEntries = [
  ["keeper-thirteen", "Keeper Thirteen", "characters/Keeper_Thirteen.md", "restricted"],
  ["silas-rook", "Silas Rook", "characters/Silas_Rook_The_Stillmaker.md", "major spoiler"],
  ["ashen-cartographer", "The Ashen Cartographer", "characters/The_Ashen_Cartographer.md", "mysterious"],
  ["bellmaker", "The Bellmaker", "characters/The_Bellmaker.md", "mysterious"],
  ["cinder-regent", "The Cinder Regent", "characters/The_Cinder_Regent.md", "restricted"],
  ["curator", "The Curator", "characters/The_Curator.md", "restricted"],
  ["first-mechanist", "The First Mechanist", "characters/The_First_Mechanist.md", "mysterious"],
  ["first-tender", "The First Tender", "characters/The_First_Tender.md", "restricted"],
  ["hidden-architect", "The Hidden Architect", "characters/The_Hidden_Architect_Unassigned.md", "ultimate spoiler"],
  ["lady-in-the-water", "The Lady in the Water", "characters/The_Lady_in_the_Water.md", "mysterious"],
  ["null-shepherd", "The Null Shepherd", "characters/The_Null_Shepherd.md", "mysterious"],
  ["passenger-of-dock-zero", "The Passenger of Dock Zero", "characters/The_Passenger_of_Dock_Zero.md", "mysterious"],
].map(([slug, title, sourcePath, sensitivity]) => hiddenStub({
  id: `hidden-character-${slug}`,
  slug,
  entityType: "character",
  title,
  sourcePath,
  sensitivity,
  publicSummary: title === "The Hidden Architect"
    ? "A concealed future role recorded only as a restricted designation. The identity remains sealed, withheld, and deliberately unassigned."
    : `${title} is indexed as a ${sensitivity} figure. Identity and fuller context remain sealed or withheld from the public catalog.`,
}));

export const hiddenOrganizationEntries = [
  ["ash-detail", "The Ash Detail", "The_Ash_Detail.md"],
  ["cinder-wardens", "The Cinder Wardens", "The_Cinder_Wardens.md"],
  ["clockkeepers-without-hours", "The Clockkeepers Without Hours", "The_Clockkeepers_Without_Hours.md"],
  ["furnace-court", "The Furnace Court", "The_Furnace_Court.md"],
  ["inner-compass", "The Inner Compass", "The_Inner_Compass.md"],
  ["keepers-of-time", "The Keepers of Time", "The_Keepers_of_Time.md"],
  ["ninth-guild", "The Ninth Guild", "The_Ninth_Guild.md"],
  ["order-of-the-closed-eye", "The Order of the Closed Eye", "The_Order_of_the_Closed_Eye.md"],
  ["quiet-choir", "The Quiet Choir", "The_Quiet_Choir.md"],
  ["underclock", "The Underclock", "The_Underclock.md"],
].map(([slug, title, filename]) => hiddenStub({
  id: `hidden-organization-${slug}`,
  slug,
  entityType: "organization",
  title,
  sourcePath: `organizations/${filename}`,
  sensitivity: "restricted",
}));

export const hiddenArchiveEntries = [
  ...hiddenMapEntries,
  ...hiddenCharacterEntries,
  ...hiddenOrganizationEntries,
];
